name: Deploy GUI Part

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Package GUI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build Binary with PyInstaller
        run: |
          pyinstaller gui/main.py --onefile --noconsole --name visual-rsa

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: visual-rsa-${{ matrix.os }}
          path: |
            dist/visual-rsa.exe
            dist/visual-rsa
          if-no-files-found: ignore

  release:
    name: Create Release and Upload Binaries
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: visual-rsa-${{ matrix.os }}
          path: binaries

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            binaries/visual-rsa.exe
            binaries/visual-rsa
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: |
            This release contains the latest binaries for the visual-rsa GUI application.
          draft: false
          prerelease: false
